### PR TITLE
[Feature] New Data Modeling

### LINKED ISSUE #3: Inexisting data modeling
The current implementation lacks data modeling, being the data that traffics between layers an unconstrained python dictionary.

> The main purpose of modeling your data is to have a centralized source of truth for each of the complex types of interest in the application, and to ensure that they always follow the model's constraints.

To implement this, I would like you to use the [schematics](https://schematics.readthedocs.io/en/latest/) package to define a model for the weather object.

While you're at it, please, keeping the information currently returned, also return: 
- visibility, wind speed and wind degree.
- minimum and maximum temperature and temperature sensation, but only if each of them differ from the main temperature.

Also, all information that depends on an unit of measurement should have it stated explicitly.

### LINKED ISSUE #6: Unit tests are not independent
In the `test_weather_list_get`, it is asserted that the weather data for the city of London is returned by the `/weather` endpoint. However, `/weather` returns the cached weathers, and London's weather was never queried in this test to be expected to be in cache.

```python
def test_weather_list_get(client):

    client.get('/weather/Toronto')
    client.get('/weather/Amsterdam')
    client.get('/weather/Berlin')
    client.get('/weather/Oslo')

    response = client.get('/weather')

    assert response.status_code == 200
    assert len(response.json) == 5
    assert response.json[0]['city'] == 'Oslo'
    assert response.json[4]['city'] == 'London'

    response = client.get('/weather?max=3')

    assert len(response.json) == 3
```

Since, still, this test passes, it is an example that shows clearly that the current unit tests are not independent, nor running in isolation to one another.

> If the tests can not run independently then they are not unit tests.
> 
> A unit test should not rely on any external state, such as contents of a database table. It should purely test one unit of code in isolation.
>
> (extracted from [StackExchange](https://softwareengineering.stackexchange.com/questions/64306/should-each-unit-test-be-able-to-be-run-independently-of-other-tests#answer-64308))

Flask's documentation on tests hints on how to handle this regarding databases. In our case, though, the external state that is influencing tests is not the one of a database, but the one of the cache.

### PR DESCRIPTION
**Pull request by rarycoringa**
This PR change the management of data requests. Following the guidelines, the [Schematics](https://schematics.readthedocs.io/en/latest/index.html) was used to model the Weather object.

- Weather object instance now looks like this:
```json
{
   "city": {
      "name": "London",
      "country": "GB",
      "coordinates": [
         51.5085,
         -0.1257
      ]
   },
   "description": "Clouds",
   "long_description": "Broken Clouds",
   "temperature": {
      "value": 5.54,
      "unit": "celsius degree"
   },
   "feels_like": {
      "value": 2.76,
      "unit": "celsius degree"
   },
   "max_temperature": {
      "value": 6.11,
      "unit": "celsius degree"
   },
   "min_temperature": {
      "value": 5.0,
      "unit": "celsius degree"
   },
   "wind": {
      "speed": {
         "value": 3.6,
         "unit": "meters per second"
      },
      "degree": {
         "value": 100.0,
         "unit": "degrees"
      }
   },
   "visibility": {
      "value": 10000.0,
      "unit": "meters"
   }
}
```
> **Note:** The `feels_like`, `max_temperature` and `min_temperature` are collected and returned only if they are not equal to the main temperature.

- The Resources and Requests has been changed to be compatible at new Weather object model.

### CODE REVIEW

**Comment by rarycoringa** [comment]
Because of the new modeling, I chose not to include the branch develop in the branch list to run the tests via GitHub Actions. They will probably to break.

This problem will be solved in the next PR, where I will refactor the tests and generate coverage reports.

**Comment by dluiscosta** [comment]
> Because of the new modeling, I chose not to include the branch develop in the branch list to run the tests via GitHub Actions. They will probably to break.
> 
> This problem will be solved in the next PR, where I will refactor the tests and generate coverage reports.

@rarygc, this is not the correct approach. The scope of this PR is the one of adding data modeling as a technical enhancement and adding new fields as a new feature, already tested and guaranteed not to break previous features, so it should also update the tests accordingly (even if it means refactoring them). No changes should be ever accepted with breaking tests, nor should them be disabled.

If doing this conflicts with another ongoing PR, you can just re-prioritize in order to avoid rework.

**Comment by rarycoringa** [comment]
> @rarygc, this is not the correct approach. The scope of this PR is the one of adding data modeling as a technical enhancement and adding new fields as a new feature, already tested and guaranteed not to break previous features, so it should also update the tests accordingly (even if it means refactoring them). No changes should be ever accepted with breaking tests, nor should them be disabled.
> 
> If doing this conflicts with another ongoing PR, you can just re-prioritize in order to avoid rework.
> 

@dluiscosta 

All right, got it!

So I’m going to update this PR with the new modeling, including the tests refactor.

*Thanks for the  guidance!*

**Comment by rarycoringa** [comment]
This PR is ready to be reviewed and merged with the develop branch.

The API test suite has also been refactored to be compatible with the new model.

The following issues will be resolved:
- [x] Issue #3 
- [x] Issue #6

**Pull request merged**
